include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/binary-flatpak.yml

variables:
  BUNDLE: org.kde.keysmith.flatpak

flatpak:
  extends: .flatpak
  variables:
    MANIFEST_PATH: org.kde.keysmith.json
    APP_ID: org.kde.keysmith
    FLATPAK_MODULE: org.kde.keysmith
    CMAKE_ARGS: -DENABLE_TESTING=OFF
