#
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2019 Bhushan Shah <bshah@kde.org>
# SPDX-FileCopyrightText: 2019-2020 Johan Ouwerkerk <jm.ouwerkerk@gmail.com>
# SPDX-FileCopyrightText: 2020 Nicolás Alvarez
#

include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-extragear-linux.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-extragear-freebsd.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-reuse.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-static-analysis.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/binary-flatpak.yml

variables:
  BUNDLE: org.kde.keysmith.flatpak

flatpak:
  extends: .flatpak
  variables:
    MANIFEST_PATH: org.kde.keysmith.json
    APP_ID: org.kde.keysmith
    FLATPAK_MODULE: org.kde.keysmith
    CMAKE_ARGS: -DBUILD_TESTING=OFF

# needed for the static analysis jobs below
.linux:
  artifacts:
    paths:
      - build

static-analysis-linux-merge-request:
  extends: .static-analysis-linux-merge-request

static-analysis-linux-commit:
  extends: .static-analysis-linux-commit
