#
# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2019 Bhushan Shah <bshah@kde.org>
# SPDX-FileCopyrightText: 2019-2020 Johan Ouwerkerk <jm.ouwerkerk@gmail.com>
# SPDX-FileCopyrightText: 2020 Nicolás Alvarez
#

include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-extragear-freebsd.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-reuse.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-static-analysis.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/binary-flatpak.yml

variables:
  BUNDLE: org.kde.keysmith.flatpak
  BRANCH_GROUP: kf5-qt5
  PRODUCT: Extragear

flatpak:
  extends: .flatpak
  variables:
    MANIFEST_PATH: org.kde.keysmith.json
    APP_ID: org.kde.keysmith
    FLATPAK_MODULE: org.kde.keysmith
    CMAKE_ARGS: -DBUILD_TESTING=OFF

#
# Build jobs for Qt 5.15 which are not provided by CI templates (yet).
#

android kf5-qt5 qt5.15:
  image: "kdeorg/ci-android"
  extends: .android
  only:
    - master
    - merge_requests
  variables:
    PLATFORM: AndroidQt5.15

linux kf5-qt5 qt5.15:
  image: "kdeorg/ci-suse-qt515"
  extends: .linux
  only:
    - master
    - merge_requests
  variables:
    PLATFORM: SUSEQt5.15

#
# Add static analysis jobs for Qt 5.15 builds.
#

static-analysis-linux-merge-request kf5-qt5 qt5.15:
  extends: .static-analysis-linux-merge-request
  image: "kdeorg/ci-suse-qt515"
  variables:
    PLATFORM: SUSEQt5.15
  dependencies:
    - linux kf5-qt5 qt5.15

static-analysis-linux-commit kf5-qt5 qt5.15:
  extends: .static-analysis-linux-commit
  image: "kdeorg/ci-suse-qt515"
  variables:
    PLATFORM: SUSEQt5.15
  dependencies:
    - linux kf5-qt5 qt5.15
