# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kguiaddons': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/prison': 'Frameworks/6.24'
    'libraries/kirigami-addons': 'v1.11.0'

 - 'on': ['Linux', 'FreeBSD']
   'require':
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/qqc2-desktop-style': 'Frameworks/6.24'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
