# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/kwidgetsaddons': '@stable'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kwindowsystem': '@stable'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
