version = 1
SPDX-PackageName = "Keysmith"
SPDX-PackageDownloadLocation = "https://invent.kde.org/kde/keysmith.git"

[[annotations]]
path = "android/res/drawable/keysmith.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Nicolas Fella <nicolas.fella@gmx.de>, 2020 Carson Black <uhhadd@gmail.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "po/**/**.po"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 KDE Localization team <kde-i18n-doc@kde.org>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "po/po/ca/keysmith.po"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 KDE Localization team <kde-i18n-doc@kde.org>"
SPDX-License-Identifier = "LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL"

[[annotations]]
path = "po/ca@valencia/keysmith.po"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 KDE Localization team <kde-i18n-doc@kde.org>"
SPDX-License-Identifier = "LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL"

[[annotations]]
path = "po/uk/keysmith.po"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 KDE Localization team <kde-i18n-doc@kde.org>"
SPDX-License-Identifier = "LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL"
